/*
 Copyright 2016 IoT.bzh

 author: José Bollo <jose.bollo@iot.bzh>

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

#define _GNU_SOURCE

#include <stdlib.h>
#include <stdio.h>
#include <sys/types.h>
#include <fcntl.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>

#include "wgt-info.h"
#include "wgt-names.h"

#include "mustach.h"


static const char default_unit[] = "\
# auto generated by wgtpkg-unit for {{id}} version {{version}}\n\
\n\
[Unit]\n\
Description={{description}}\n\
{{#required-binding}}\
Requires={{required-binding-name}}\n\
After={{required-binding-name}}\n\
{{/required-binding}}\
\n\
[Service]\n\
";

static const char str_description[] = "description";
static const char str_id[] = "id";
static const char str_required_binding[] = "required-binding";
static const char str_required_binding_name[] = "required-binding-name";
static const char str_version[] = "version";

struct _m_ {
	const struct wgt_desc *desc;
	const struct wgt_desc_feature *feature;
	const struct wgt_desc_param *param;
	enum {
		_m_root,
		_m_required_binding,
	} state;
};

static int _m_write_escaped(const char *string, FILE *file)
{
	int idx = 0;
	while(string[idx]) {
		if (string[idx++] == '\n') {
			if (idx)
				fprintf(file, "%.*s", idx-1, string);
			fprintf(file, "\\n");
			string = &string[idx + 1];
			idx = 0;
		}
	}
	fprintf(file, "%s", string);
	return 0;
}

static int _m_write_unescaped(const char *string, FILE *file)
{
	int idx = 0;
	while(string[idx] && string[idx] != '\n')
		idx++;
	if (idx)
		fprintf(file, "%.*s" "\\n", idx-1, string);
	return 0;
}

static int _m_write(const char *string, FILE *file, int escape)
{
	if (!string)
		string = "";
	return escape ? _m_write_escaped(string, file) : _m_write_unescaped(string, file);
}

static int _m_enter_param(struct _m_ *m, const char *param)
{
	m->param = m->feature ? m->feature->params : NULL;
	while (m->param) {
		if (!param || !strcmp(param, m->param->name))
			return 1;
		m->param = m->param->next;
	}
	return 0;
}

static int _m_next_param(struct _m_ *m, const char *param)
{
	m->param = m->param ? m->param->next : NULL;
	while (m->param) {
		if (!param || !strcmp(param, m->param->name))
			return 1;
		m->param = m->param->next;
	}
	return 0;
}

static int _m_enter_feature(struct _m_ *m, const char *feature)
{
	m->param = NULL;
	m->feature = m->desc->features;
	while (m->feature) {
		if (!feature || !strcmp(feature, m->feature->name))
			return 1;
		m->feature = m->feature->next;
	}
	return 0;
}

static int _m_next_feature(struct _m_ *m, const char *feature)
{
	m->param = NULL;
	m->feature = m->feature ? m->feature->next : NULL;
	while (m->feature) {
		if (!feature || !strcmp(feature, m->feature->name))
			return 1;
		m->feature = m->feature->next;
	}
	return 0;
}

static int _m_enter_both(struct _m_ *m, const char *feature, const char *param)
{
	if (!_m_enter_feature(m, feature))
		return 0;
	while(!_m_enter_param(m, param))
		if (!_m_next_feature(m, feature))
			return 0;
	return 1;
}

static int _m_next_both(struct _m_ *m, const char *feature, const char *param)
{
	if(_m_next_param(m, param))
		return 1;
	do {
		if (!_m_next_feature(m, feature))
			return 0;
	} while(!_m_enter_param(m, param));
	return 1;
}

static int _m_start(void *closure)
{
	struct _m_ *m = closure;
	m->state = _m_root;
	m->feature = NULL;
	m->param = NULL;
	return 0;
}

static int _m_put(void *closure, const char *name, int escape, FILE *file)
{
	struct _m_ *m = closure;

	if (!strcmp(name, str_id))
		return _m_write(m->desc->id, file, escape);

	if (!strcmp(name, str_version))
		return _m_write(m->desc->version, file, escape);

	if (!strcmp(name, str_description))
		return _m_write(m->desc->description, file, escape);

	if (!strcmp(name, str_required_binding_name) && m->state == _m_required_binding)
		return _m_write(m->param->name, file, escape);

	return 0;
}

static int _m_enter(void *closure, const char *name)
{
	struct _m_ *m = closure;

	if (m->state != _m_root)
		return 0;

	if (!strcmp(name, str_required_binding)) {
		if (!_m_enter_both(m, feature_required_binding, NULL))
			return 0;
		m->state = _m_required_binding;
		return 1;
	}

	return 0;
}

static int _m_next(void *closure)
{
	struct _m_ *m = closure;
	switch (m->state) {
	case _m_required_binding:
		return _m_next_both(m, feature_required_binding, NULL);
	default:
		break;
	}
	return 0;
}

static int _m_leave(void *closure)
{
	struct _m_ *m = closure;
	switch (m->state) {
	case _m_required_binding:
		m->state = _m_root;
		break;
	default:
		break;
	}
	return 0;
}

static struct mustach_itf _m_itf = {
	.start = _m_start,
	.put = _m_put,
	.enter = _m_enter,
	.next = _m_next,
	.leave = _m_leave,
	.partial = NULL
};

int unit_fwrite(FILE *file, const struct wgt_desc *desc, const char *template)
{
	struct _m_ m;
	int rc;

	/* init */
	clearerr(file);
	m.desc = desc;

	/* emit */
	rc = fmustach(template, &_m_itf, &m, file);
	if (rc == 0) {
		/* check file status */
		rc = ferror(file);
		if (rc) {
			errno = rc;
			rc = -1;
		}
	}

	return rc;
}

int fwrite_unit(const struct wgt_desc *desc, FILE *file)
{
	return unit_fwrite(file, desc, default_unit);
}

int get_unit(const struct wgt_desc *desc, char **buffer, size_t *size)
{
	int rc;
	FILE *f;

	f = open_memstream(buffer, size);
	if (f == NULL)
		rc = -1;
	else {
		*buffer = NULL;
		rc = fwrite_unit(desc, f);
		if (rc >= 0)
			fwrite(&rc, 1, 1, f);
		fclose(f);
		if (rc < 0)
			free(*buffer);
		else
			(*size)--;
	}
	return rc;
}

