/*
 Copyright 2016 IoT.bzh

 author: José Bollo <jose.bollo@iot.bzh>

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

#define _GNU_SOURCE

#include <stdlib.h>
#include <stdio.h>
#include <sys/types.h>
#include <fcntl.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>

#include "wgt-info.h"
#include "wgt-names.h"

#include "mustach.h"


static const char default_unit[] = "\
# auto generated by wgtpkg-unit for {{id}} version {{version}}\n\
\n\
[Unit]\n\
Description={{description}}\n\
{{#urn:AGL:required-binding}}\
{{#param}}\
Requires={{name}}\n\
After={{name}}\n\
{{/param}}\
{{/urn:AGL:required-binding}}\
\n\
[Service]\n\
";

static const char str_description[] = "description";
static const char str_id[] = "id";
static const char str_name[] = "name";
static const char str_optional[] = "optional";
static const char str_param[] = "param";
static const char str_required[] = "required";
static const char str_version[] = "version";

struct _m_ {
	const struct wgt_desc *desc;
	const struct wgt_desc_feature *feature;
	const struct wgt_desc_param *param;
	int in_feature_value;
	int any_param;
	int in_param_value;
};

static int _m_write_escaped(const char *string, FILE *file)
{
	int idx = 0;
	while(string[idx]) {
		if (string[idx++] == '\n') {
			if (idx)
				fprintf(file, "%.*s", idx-1, string);
			fprintf(file, "\\n");
			string = &string[idx + 1];
			idx = 0;
		}
	}
	fprintf(file, "%s", string);
	return 0;
}

static int _m_write_unescaped(const char *string, FILE *file)
{
	int idx = 0;
	while(string[idx] && string[idx] != '\n')
		idx++;
	if (idx)
		fprintf(file, "%.*s" "\\n", idx-1, string);
	return 0;
}

static int _m_write(const char *string, FILE *file, int escape)
{
	if (!string)
		string = "";
	return escape ? _m_write_escaped(string, file) : _m_write_unescaped(string, file);
}

static int _m_write_bool(int value, FILE *file, int escape)
{
	return _m_write(value ? "true" : "false", file, escape);
}

static const struct wgt_desc_feature *seek_feature(const struct wgt_desc_feature *feature, const char *name)
{
	while (feature && strcmp(feature->name, name))
		feature = feature->next;
	return feature;
}

static int _m_feature(struct _m_ *m, const struct wgt_desc_feature *feature, const char *name)
{
	feature = seek_feature(feature, name);
	if (!feature)
		return 0;

	m->feature = feature;
	m->param = NULL;
	return 1;
}

static int _m_param(struct _m_ *m, const struct wgt_desc_param *param, const char *name)
{
	const struct wgt_desc_feature *feature = m->feature;
	while (feature) {
		while (param) {
			if (m->any_param || !strcmp(param->name, name)) {
				m->feature = feature;
				m->param = param;
				return 1;
			}
			param = param->next;
		}
		feature = seek_feature(feature->next, feature->name);
		if (feature)
			param = feature->params;
	}
	return 0;
}

static int _m_start(void *closure)
{
	struct _m_ *m = closure;
	m->feature = NULL;
	m->param = NULL;
	m->in_feature_value = 0;
	m->any_param = 0;
	m->in_param_value = 0;
	return 0;
}

static int _m_put(void *closure, const char *name, int escape, FILE *file)
{
	struct _m_ *m = closure;

	if (!strcmp(name, str_id))
		return _m_write(m->desc->id, file, escape);

	if (!strcmp(name, str_description))
		return _m_write(m->desc->description, file, escape);

	if (!strcmp(name, str_name) && m->param)
		return _m_write(m->param->name, file, escape);

	if (!strcmp(name, str_required) && m->feature)
		return _m_write_bool(m->feature->required, file, escape);

	if (!strcmp(name, str_version))
		return _m_write(m->desc->version, file, escape);

	return 0;
}

static int _m_enter(void *closure, const char *name)
{
	struct _m_ *m = closure;

	if (!m->feature)
		return _m_feature(m, m->desc->features, name);
	if (!m->param && !m->in_feature_value) {
		if (!strcmp(name, m->feature->required ? str_required : str_optional)) {
			m->in_feature_value = 1;
			return 1;
		}
	}
	if (!m->param) {
		m->any_param = !strcmp(str_param, name);
		return _m_param(m, m->feature->params, name);
	}
	if (!m->in_param_value) {
		if (!strcmp(m->param->value, name)) {
			m->in_param_value = 1;
			return 1;
		}
	}
	return 0;
}

static int _m_next(void *closure)
{
	struct _m_ *m = closure;
	if (m->in_param_value)
		return 0;
	if (m->param)
		return _m_param(m, m->param->next, m->param->name);
	if (m->in_feature_value)
		return 0;
	if (m->feature)
		return _m_feature(m, m->feature->next, m->feature->name);
	return 0;
}

static int _m_leave(void *closure)
{
	struct _m_ *m = closure;

	if (m->in_param_value)
		m->in_param_value = 0;
	else if (m->param) {
		m->param = NULL;
		m->any_param = 0;
	} else if (m->in_feature_value)
		m->in_feature_value = 0;
	else if (m->feature)
		m->feature = NULL;
	return 0;
}

static struct mustach_itf _m_itf = {
	.start = _m_start,
	.put = _m_put,
	.enter = _m_enter,
	.next = _m_next,
	.leave = _m_leave,
	.partial = NULL
};

int unit_fwrite(FILE *file, const struct wgt_desc *desc, const char *template)
{
	struct _m_ m;
	int rc;

	/* init */
	clearerr(file);
	m.desc = desc;

	/* emit */
	rc = fmustach(template, &_m_itf, &m, file);
	if (rc == 0) {
		/* check file status */
		rc = ferror(file);
		if (rc) {
			errno = rc;
			rc = -1;
		}
	}

	return rc;
}

int fwrite_unit(const struct wgt_desc *desc, FILE *file)
{
	return unit_fwrite(file, desc, default_unit);
}

int get_unit(const struct wgt_desc *desc, char **buffer, size_t *size)
{
	int rc;
	FILE *f;

	f = open_memstream(buffer, size);
	if (f == NULL)
		rc = -1;
	else {
		*buffer = NULL;
		rc = fwrite_unit(desc, f);
		if (rc >= 0)
			fwrite(&rc, 1, 1, f);
		fclose(f);
		if (rc < 0)
			free(*buffer);
		else
			(*size)--;
	}
	return rc;
}

